# Generated by Django 5.0 on 2023-12-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="student_number",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
